### ISSUE TITLE
tokenv2createtokel user input checks

### ISSUE THREAD

**Issue by Alrighttt** [TokelPlatform/tokel#32]
This check does not properly account for all possibilities. 
https://github.com/TokelPlatform/komodo/blob/0816254e2bccd007494ce080d2d5c1ac8cbeb18a/src/rpc/tokensrpc.cpp#L484

The issue can be reproduced with the following command or similar: 
`komodo-cli -ac_name=TKLTEST2 tokenv2createtokel name 0.00001 desc "{A BROKEN JSON}"`

This type of error in the user input is not accounted for correctly. It results in the token being created with a data field of `"data": "f701"`. 

@dimxy

**Comment by dimxy** [comment]
this is how Univalue parses it. Maybe we should check if this is resolved in the upstream and pull the updates

**Comment by dimxy** [comment]
update:
Univalue::read returns a boolean result that should be checked. 
(why does it return an empty object though if the source is invalid?)

**Comment by dimxy** [comment]
fixed in the tokel branch already (with the latest update)
