### ISSUE TITLE
dPoW hardfork pubkeys update

### ISSUE THREAD

**Issue by smk762** [TokelPlatform/tokel#50]
The KMD hardfork update for season 7 has been released :tada: and is scheduled for the 30th of June.
Your will need to update the TOKEL code to include the new pubkeys and calculate an estimated TOKEL block height that corresponds to close to the same date / time.

You can reference this pull request to get the required changes https://github.com/KomodoPlatform/AYAv2/pull/5

**Comment by CHMEX** [comment]
https://github.com/TokelPlatform/tokel/commit/6c08e00c9dc3ceb40550f1d528593d8c2149214c

added last hash: 6c08e00c9dc3ceb40550f1d528593d8c2149214c

**Comment by CHMEX** [comment]
added some version stuff latest f1fc997c5b66ea53992c77a8478aa5a157c4fbc3

**Comment by CHMEX** [comment]
before
 "version": 3000000,
  "protocolversion": 170010,
  "KMDversion": "0.6.0",
  "TokelVersion": "0.3.2",
  "synced": true,
  "notarized": 882372,
  "prevMoMheight": 882372,
  "notarizedhash": "000035ab2070e
after
 "version": 3000000,
  "protocolversion": 170011,
  "KMDversion": "0.6.0",
  "TokelVersion": "0.3.3",
  "synced": false,
  "notarized": 882372,
  "prevMoMheight": 882372,
  "notarizedhash": "000035ab2070e

**Comment by dimxy** [comment]
The end-of-season timestamp and height are not updated like in komodo:
```
static const uint32_t KMD_SEASON_TIMESTAMPS[NUM_KMD_SEASONS] = {..., nS7Timestamp, 1951328000};
static const int32_t KMD_SEASON_HEIGHTS[NUM_KMD_SEASONS] = {..., nS7HardforkHeight, 8113400};
```

**Comment by CHMEX** [comment]
>
>
> Yes TOKEL are set to year 2028 and not year 2031. Hopefully he have
another update in between.
I hope the rest is OK?

**Comment by dimxy** [comment]
the rest looks good
I added tests for S7 to make sure https://github.com/dimxy/komodo/tree/notary-s7-test

**Comment by dimxy** [comment]
approved

**Comment by Alrighttt** [comment]
LGTM
